# Networking
CONFIG_NETWORKING=y
CONFIG_NET_IPV4=y
CONFIG_NET_DHCPV4=y
CONFIG_NET_TCP=y
CONFIG_NET_SOCKETS=y
CONFIG_NET_HOSTNAME_ENABLE=y
CONFIG_POSIX_API=y              # for socket/networking funcitons like getaddrinfo

# WiFi
CONFIG_WIFI=y
CONFIG_NET_L2_WIFI_MGMT=y
CONFIG_NET_MGMT=y
CONFIG_NET_MGMT_EVENT=y
CONFIG_NET_MGMT_EVENT_INFO=y

# WiFi credentials
CONFIG_WIFI_SSID="Jacks iPhone"
CONFIG_WIFI_PSK="wordpass"      # password in the commit!1 :flushed:

# MQTT
CONFIG_MQTT_LIB=y
CONFIG_NET_SAMPLE_MQTT_BROKER_HOSTNAME="172.20.10.10"   # static IP address PC uses
CONFIG_NET_SAMPLE_MQTT_BROKER_PORT="1883"               # standard MQTT insecure port
CONFIG_NET_SAMPLE_MQTT_SUB_TOPIC_CMD="brake/request"
CONFIG_NET_SAMPLE_MQTT_PUB_TOPIC="brake/state"
CONFIG_NET_SAMPLE_MQTT_QOS_0_AT_MOST_ONCE=y
CONFIG_NET_SAMPLE_MQTT_PUBLISH_INTERVAL_MS=1000

# JSON
CONFIG_JSON_LIBRARY=y

# ADC
CONFIG_ADC=y

# PWM
CONFIG_PWM=y

# Stack sizes for ESP32
CONFIG_MAIN_STACK_SIZE=4096
CONFIG_NET_TX_STACK_SIZE=2048
CONFIG_NET_RX_STACK_SIZE=2048

# Network buffers
CONFIG_NET_PKT_RX_COUNT=10
CONFIG_NET_PKT_TX_COUNT=10
CONFIG_NET_BUF_RX_COUNT=20
CONFIG_NET_BUF_TX_COUNT=20

# Logging
CONFIG_LOG=y
CONFIG_NET_LOG=y
CONFIG_LOG_DEFAULT_LEVEL=3
